version: "3.8"
services:
  web:
    build: 
      context: ./WebApp
    ports:
      - "9999:5000"
    volumes:
      - ./WebApp:/code
  redis:
    image: "redis:6.0.9-alpine"
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/redis.conf
    command: /bin/sh -c "redis-server --appendonly yes"
